# Generated by Django 6.0.5 on 2026-06-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('atendimento', 'Em Atendimento'), ('finalizado', 'Finalizado'), ('reagendar', 'Reagendar'), ('faltou', 'Faltou'), ('cancelado', 'Cancelado')], default='agendado', max_length=20),
        ),
    ]
