# Generated by Django 6.0.5 on 2026-07-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_profissional_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='duracao',
            field=models.PositiveIntegerField(default=60, help_text='Duração em minutos'),
        ),
    ]
