# Generated by Django 6.0.5 on 2026-05-20 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_paciente_alergias_paciente_bairro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possui_alergia', models.BooleanField(default=False)),
                ('alergias', models.TextField(blank=True)),
                ('usa_medicamento', models.BooleanField(default=False)),
                ('medicamentos', models.TextField(blank=True)),
                ('possui_doenca', models.BooleanField(default=False)),
                ('doencas', models.TextField(blank=True)),
                ('gravida', models.BooleanField(default=False)),
                ('hipertenso', models.BooleanField(default=False)),
                ('diabetico', models.BooleanField(default=False)),
                ('fumante', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('sangramento_gengival', models.BooleanField(default=False)),
                ('sensibilidade', models.BooleanField(default=False)),
                ('dor_mastigar', models.BooleanField(default=False)),
                ('bruxismo', models.BooleanField(default=False)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.paciente')),
            ],
        ),
    ]
