# Generated by Django 6.0.5 on 2026-05-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_anamnese'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anamnese',
            old_name='dor_mastigar',
            new_name='abandono_tratamento',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='sangramento_gengival',
            new_name='anemia',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='sensibilidade',
            new_name='asma',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='ultima_atualizacao',
            new_name='atualizado_em',
        ),
        migrations.AddField(
            model_name='anamnese',
            name='bronquite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='cardiopatia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='cirurgias',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='escova_frequencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='escova_lingua',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='experiencia_odontologica',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='faz_tratamento_medico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='hepatite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='morde_objetos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='pressao_arterial',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='queixa_principal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='respiracao_bucal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='roer_unhas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='ronco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='transfusao_sangue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='tratamento_medico',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='ultima_consulta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='usa_fio_dental',
            field=models.BooleanField(default=False),
        ),
    ]
