# Generated by Django 6.0.5 on 2026-05-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_dor_mastigar_anamnese_abandono_tratamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnese',
            name='doencas',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='escova_frequencia',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='faz_tratamento_medico',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='possui_alergia',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='possui_doenca',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='pressao_arterial',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='tratamento_medico',
        ),
        migrations.AddField(
            model_name='anamnese',
            name='agitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='alergico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='analgesicos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='anestesia_reacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='ansioso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='antibioticos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='antiinflamatorios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='calmo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='chupeta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='comunicativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='frequencia_escovacao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='historico_medico',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='hospitalizacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='medo_dentista',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='retraido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='succao_dedo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='usa_enxaguante',
            field=models.BooleanField(default=False),
        ),
    ]
