# Generated by Django 6.0.5 on 2026-05-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_anamnese_doencas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='baba_travesseiro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='cirurgia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='dor_mastigar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='hospitalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='primeira_consulta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='sangramento_gengival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='sensibilidade',
            field=models.BooleanField(default=False),
        ),
    ]
