# Generated by Django 6.0.5 on 2026-05-20 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_anamnese_baba_travesseiro_anamnese_cirurgia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolucaoClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dente', models.CharField(blank=True, max_length=10)),
                ('procedimento', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('materiais', models.TextField(blank=True)),
                ('anestesia', models.CharField(blank=True, max_length=255)),
                ('retorno', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes', to='accounts.paciente')),
            ],
        ),
    ]
