# Generated by Django 6.0.5 on 2026-05-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_evolucaoclinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='alimentacao_cariogenica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='belisca_refeicoes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='dorme_boca_aberta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='extrovertido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='introvertido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='morde_labios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='problema_renal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='rinite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='sangramento_excessivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='sinusite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='tipo_alimentacao',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
