# Generated by Django 6.0.5 on 2026-05-21 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_anamnese_alimentacao_cariogenica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('dente', 'Por Dente'), ('hemiarcada', 'Hemi-Arcada'), ('geral', 'Geral'), ('cirurgia', 'Cirurgia')], max_length=50)),
                ('cor', models.CharField(default='#2563eb', max_length=20)),
                ('icone', models.CharField(blank=True, max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='evolucaoclinica',
            name='procedimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.procedimento'),
        ),
    ]
