# Generated by Django 6.0.5 on 2026-05-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_procedimento_alter_evolucaoclinica_procedimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='posicao_icone',
            field=models.CharField(choices=[('coroa', 'Coroa'), ('raiz', 'Raiz'), ('oclusal', 'Oclusal'), ('vestibular', 'Vestibular'), ('lingual', 'Lingual'), ('centro', 'Centro')], default='coroa', max_length=30),
        ),
    ]
