# Generated by Django 6.0.5 on 2026-05-23 21:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_procedimento_posicao_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedimento',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='categoria',
            field=models.CharField(choices=[('dentistica', 'Dentística'), ('endodontia', 'Endodontia'), ('periodontia', 'Periodontia'), ('cirurgia', 'Cirurgia'), ('protese', 'Prótese'), ('implantodontia', 'Implantodontia'), ('ortodontia', 'Ortodontia'), ('geral', 'Geral')], default='geral', max_length=100),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='icone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='posicao_icone',
            field=models.CharField(choices=[('coroa', 'Coroa'), ('raiz', 'Raiz'), ('oclusal', 'Oclusal'), ('vestibular', 'Vestibular'), ('lingual', 'Lingual'), ('centro', 'Centro')], default='centro', max_length=30),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='tipo',
            field=models.CharField(choices=[('dente', 'Por Dente'), ('hemiarcada', 'Hemi-Arcada'), ('geral', 'Geral'), ('cirurgia', 'Cirurgia')], default='dente', max_length=50),
        ),
    ]
