# Generated by Django 6.0.5 on 2026-05-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_procedimento_criado_em_procedimento_ordem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimento',
            name='cor',
        ),
        migrations.AddField(
            model_name='procedimento',
            name='status',
            field=models.CharField(choices=[('realizar', 'A Realizar'), ('andamento', 'Em Andamento'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado'), ('reavaliar', 'Reavaliar')], default='realizar', max_length=30),
        ),
    ]
