# Generated by Django 6.0.5 on 2026-05-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_procedimento_cor_procedimento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='valor_convenio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='valor_particular',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
