# Generated by Django 6.0.5 on 2026-05-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_orcamento_itemorcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='custo_clinico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='tempo_estimado',
            field=models.IntegerField(default=60, help_text='Tempo em minutos'),
        ),
    ]
