# Generated by Django 6.0.5 on 2026-05-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_convenio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='valor_convenio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
