# Generated by Django 6.0.5 on 2026-05-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_procedimento_valor_convenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamento',
            name='dente',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='face',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='status',
            field=models.CharField(choices=[('planejado', 'Planejado'), ('andamento', 'Em andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='planejado', max_length=20),
        ),
    ]
