# Generated by Django 6.0.5 on 2026-05-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_itemorcamento_dente_itemorcamento_face_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemorcamento',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('aprovado', 'Aprovado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='dente',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
