# Generated by Django 6.0.5 on 2026-05-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_itemorcamento_observacoes_orcamento_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedimento',
            options={'ordering': ['categoria', 'ordem', 'nome'], 'verbose_name': 'Procedimento', 'verbose_name_plural': 'Procedimentos'},
        ),
        migrations.RemoveField(
            model_name='procedimento',
            name='icone',
        ),
        migrations.AddField(
            model_name='procedimento',
            name='arquivo_icone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='valor_convenio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
