# Generated by Django 6.0.5 on 2026-05-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_procedimento_options_remove_procedimento_icone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='icone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
