# Generated by Django 6.0.5 on 2026-05-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_procedimento_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamento',
            name='hemi_arcada',
            field=models.CharField(blank=True, choices=[('sup_dir', 'Superior Direita'), ('sup_esq', 'Superior Esquerda'), ('inf_dir', 'Inferior Direita'), ('inf_esq', 'Inferior Esquerda')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='tipo_local',
            field=models.CharField(choices=[('dente', 'Dente'), ('hemi', 'Hemi Arcada'), ('geral', 'Geral')], default='dente', max_length=20),
        ),
    ]
