# Generated by Django 6.0.5 on 2026-05-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_itemorcamento_hemi_arcada_itemorcamento_tipo_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorcamento',
            name='status',
            field=models.CharField(choices=[('existente', 'Existente'), ('planejado', 'Planejado'), ('andamento', 'Em Andamento'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='planejado', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='tipo_local',
            field=models.CharField(choices=[('dente', 'Dente'), ('hemiarcada', 'Hemi Arcada'), ('geral', 'Geral')], default='dente', max_length=20),
        ),
    ]
