# Generated by Django 6.0.5 on 2026-06-01 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_itemorcamento_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evolucaoclinica',
            name='anestesia',
        ),
        migrations.RemoveField(
            model_name='evolucaoclinica',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='evolucaoclinica',
            name='dente',
        ),
        migrations.RemoveField(
            model_name='evolucaoclinica',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='evolucaoclinica',
            name='materiais',
        ),
        migrations.RemoveField(
            model_name='evolucaoclinica',
            name='procedimento',
        ),
        migrations.RemoveField(
            model_name='evolucaoclinica',
            name='retorno',
        ),
        migrations.CreateModel(
            name='ProntuarioClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('anotacao', models.TextField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dente', models.CharField(blank=True, max_length=10)),
                ('descricao', models.TextField(blank=True)),
                ('materiais', models.TextField(blank=True)),
                ('anestesia', models.CharField(blank=True, max_length=255)),
                ('retorno', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prontuarios', to='accounts.paciente')),
                ('procedimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.procedimento')),
            ],
            options={
                'verbose_name': 'Prontuário Clínico',
                'verbose_name_plural': 'Prontuários Clínicos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
