# Generated by Django 6.0.5 on 2026-06-01 11:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_evolucaoclinica_anestesia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evolucaoclinica',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AddField(
            model_name='evolucaoclinica',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evolucaoclinica',
            name='dente',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='evolucaoclinica',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evolucaoclinica',
            name='procedimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.procedimento'),
        ),
    ]
