# Generated by Django 6.0.5 on 2026-06-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_evolucaoclinica_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucaoclinica',
            name='status',
            field=models.CharField(choices=[('existente', 'Existente'), ('planejado', 'Planejado'), ('andamento', 'Em Andamento'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='planejado', max_length=20),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='categoria',
            field=models.CharField(choices=[('diagnostico', 'Diagnóstico'), ('dentistica', 'Dentística'), ('endodontia', 'Endodontia'), ('periodontia', 'Periodontia'), ('cirurgia', 'Cirurgia'), ('protese', 'Prótese'), ('implantodontia', 'Implantodontia'), ('ortodontia', 'Ortodontia'), ('geral', 'Geral')], default='geral', max_length=100),
        ),
    ]
