# Generated by Django 6.0.5 on 2026-06-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_evolucaoclinica_status_alter_procedimento_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucaoclinica',
            name='face',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
