# Generated by Django 6.0.5 on 2026-06-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_evolucaoclinica_face'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_clinica', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinica/')),
                ('cro', models.CharField(blank=True, max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.TextField(blank=True)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('observacoes_orcamento', models.TextField(blank=True)),
            ],
        ),
    ]
