# Generated by Django 6.0.5 on 2026-06-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_configuracaoclinica'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracaoClinica',
        ),
        migrations.AlterField(
            model_name='prontuarioclinico',
            name='dente',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
