# Generated by Django 6.0.5 on 2026-06-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_configuracaoclinica_anexopaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexopaciente',
            name='tipo',
            field=models.CharField(choices=[('foto', 'Foto Clínica'), ('radiografia', 'Radiografia'), ('tomografia', 'Tomografia'), ('documento', 'Documento'), ('exame', 'Exame')], default='documento', max_length=20),
        ),
    ]
