# Generated by Django 6.0.5 on 2026-06-06 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_anexopaciente_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('consentimento', 'Termo de Consentimento'), ('receita', 'Receita'), ('atestado', 'Atestado'), ('encaminhamento', 'Encaminhamento'), ('declaracao', 'Declaração'), ('livre', 'Documento Livre')], max_length=30)),
                ('conteudo', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('finalizado', 'Finalizado')], default='rascunho', max_length=20)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='accounts.paciente')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.templatedocumento')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
