# Generated by Django 6.0.5 on 2026-06-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_templatedocumento_documentoclinico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaoclinica',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='configuracaoclinica',
            name='observacoes_orcamento',
        ),
        migrations.AlterField(
            model_name='configuracaoclinica',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
