# Generated by Django 6.0.5 on 2026-06-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_remove_configuracaoclinica_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoclinica',
            name='cnpj',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='estado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='observacoes_orcamento',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='configuracaoclinica',
            name='endereco',
            field=models.TextField(blank=True),
        ),
    ]
