# Generated by Django 6.0.5 on 2026-06-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_configuracaoclinica_cnpj_configuracaoclinica_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='anticoagulante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='bisfosfonato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='cancer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='hipertireoidismo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='hipotireoidismo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='marcapasso',
            field=models.BooleanField(default=False),
        ),
    ]
