# Generated by Django 6.0.5 on 2026-06-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_anamnese_anticoagulante_anamnese_bisfosfonato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoclinico',
            name='tipo',
            field=models.CharField(choices=[('atestado', 'Atestado'), ('declaracao', 'Declaração'), ('receita', 'Receita'), ('encaminhamento', 'Encaminhamento'), ('contrato', 'Contrato'), ('personalizado', 'Personalizado')], default='personalizado', max_length=30),
        ),
    ]
