# Generated by Django 6.0.5 on 2026-06-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_documentoclinico_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatedocumento',
            name='tipo',
            field=models.CharField(choices=[('consentimento', 'Termo de Consentimento'), ('receita', 'Receita'), ('atestado', 'Atestado'), ('encaminhamento', 'Encaminhamento'), ('declaracao', 'Declaração'), ('contrato', 'Contrato'), ('livre', 'Documento Livre')], max_length=30),
        ),
    ]
