# Generated by Django 6.0.5 on 2026-06-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_templatedocumento_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoclinico',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Documento Clínico', 'verbose_name_plural': 'Documentos Clínicos'},
        ),
        migrations.AlterField(
            model_name='documentoclinico',
            name='tipo',
            field=models.CharField(choices=[('atestado', 'Atestado Odontológico'), ('declaracao', 'Declaração de Comparecimento'), ('receita', 'Receituário Simples'), ('controle_especial', 'Receituário Controle Especial'), ('exames', 'Solicitação de Exames'), ('encaminhamento', 'Encaminhamento'), ('relatorio', 'Relatório Odontológico'), ('alta', 'Termo de Alta'), ('consentimento', 'Termo de Consentimento'), ('contrato', 'Contrato'), ('personalizado', 'Documento Personalizado')], default='personalizado', max_length=30),
        ),
        migrations.AlterField(
            model_name='templatedocumento',
            name='tipo',
            field=models.CharField(choices=[('atestado', 'Atestado Odontológico'), ('declaracao', 'Declaração de Comparecimento'), ('receita', 'Receituário Simples'), ('controle_especial', 'Receituário Controle Especial'), ('exames', 'Solicitação de Exames'), ('encaminhamento', 'Encaminhamento'), ('relatorio', 'Relatório Odontológico'), ('alta', 'Termo de Alta'), ('consentimento', 'Termo de Consentimento'), ('contrato', 'Contrato'), ('livre', 'Documento Livre')], max_length=30),
        ),
    ]
