# Generated by Django 6.0.5 on 2026-06-09 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_documentoclinico_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('concentracao', models.CharField(blank=True, max_length=100)),
                ('categoria', models.CharField(choices=[('antibiotico', 'Antibiótico'), ('analgesico', 'Analgésico'), ('antiinflamatorio', 'Anti-inflamatório'), ('antisseptico', 'Antisséptico'), ('outro', 'Outro')], default='outro', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(max_length=100)),
                ('posologia', models.TextField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('controle_especial', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.medicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='accounts.paciente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
