# Generated by Django 6.0.5 on 2026-06-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_medicamento_receita'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='status',
            field=models.CharField(default='ativo', max_length=20),
        ),
        migrations.AddField(
            model_name='receita',
            name='titulo',
            field=models.CharField(default='Receituário', max_length=200),
        ),
    ]
