# Generated by Django 6.0.5 on 2026-06-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_receita_status_receita_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='controle_especial',
        ),
        migrations.AddField(
            model_name='receita',
            name='tipo_receita',
            field=models.CharField(choices=[('simples', 'Receituário Simples'), ('controle', 'Receita de Controle Especial')], default='simples', max_length=20),
        ),
    ]
