# Generated by Django 6.0.5 on 2026-06-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_remove_receita_controle_especial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='medicamento',
            field=models.CharField(max_length=300),
        ),
    ]
