# Generated by Django 6.0.5 on 2026-06-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_receita_medicamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('medicamento', models.CharField(max_length=255)),
                ('quantidade', models.CharField(blank=True, max_length=100)),
                ('posologia', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modelo de Receita',
                'verbose_name_plural': 'Modelos de Receita',
                'ordering': ['nome'],
            },
        ),
    ]
