# Generated by Django 6.0.5 on 2026-06-11 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_exame'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='exames/'),
        ),
        migrations.AddField(
            model_name='exame',
            name='data_exame',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SolicitacaoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('exames_solicitados', models.TextField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_exames', to='accounts.paciente')),
            ],
            options={
                'verbose_name': 'Solicitação de Exame',
                'verbose_name_plural': 'Solicitações de Exames',
                'ordering': ['-criado_em'],
            },
        ),
    ]
