# Generated by Django 6.0.5 on 2026-06-14 18:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_evolucaoclinica_posicao_icone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaoclinica',
            options={'verbose_name': 'Configuração da Clínica', 'verbose_name_plural': 'Configurações da Clínica'},
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='cep',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracaoclinica',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
