# Generated by Django 6.0.5 on 2026-06-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_alter_configuracaoclinica_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamento',
            name='posicao_icone',
            field=models.CharField(blank=True, choices=[('coroa', 'Coroa'), ('raiz', 'Raiz'), ('oclusal', 'Oclusal'), ('vestibular', 'Vestibular'), ('lingual', 'Lingual'), ('centro', 'Centro')], max_length=20, null=True),
        ),
    ]
