# Generated by Django 6.0.5 on 2026-06-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_perfilusuario_assinatura_perfilusuario_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='sexo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
