# Generated by Django 6.0.5 on 2026-06-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_paciente_dentista_alter_fornecedor_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('estoque', models.IntegerField(default=0)),
                ('estoque_minimo', models.IntegerField(default=0)),
                ('valor_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
