# Generated by Django 6.0.5 on 2026-06-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_compra_itemcompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='arquivo_nf',
            field=models.FileField(blank=True, null=True, upload_to='compras/notas_fiscais/'),
        ),
    ]
