# Generated by Django 6.0.5 on 2026-06-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_compra_arquivo_nf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='arquivo_nf',
            field=models.FileField(blank=True, null=True, upload_to='notas_fiscais/'),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
