# Generated by Django 6.0.5 on 2026-06-20 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_contapagar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='accounts.compra'),
        ),
    ]
