# Generated by Django 6.0.5 on 2026-06-22 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_alter_contapagar_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vencimento', models.DateField()),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDO', 'Recebido'), ('VENCIDO', 'Vencido')], default='PENDENTE', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to='accounts.orcamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='accounts.paciente')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['vencimento'],
            },
        ),
    ]
