# Generated by Django 6.0.5 on 2026-06-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_alter_orcamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='entrada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('debito', 'Cartão Débito'), ('credito', 'Cartão Crédito'), ('boleto', 'Boleto')], default='pix', max_length=20),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='parcelas',
            field=models.IntegerField(default=1),
        ),
    ]
