# Generated by Django 6.0.5 on 2026-06-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_orcamento_entrada_orcamento_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='parcela',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='total_parcelas',
            field=models.IntegerField(default=1),
        ),
    ]
