# Generated by Django 6.0.5 on 2026-06-25 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_contareceber_parcela_contareceber_total_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucaoclinica',
            name='item_orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolucoes', to='accounts.itemorcamento'),
        ),
        migrations.AddField(
            model_name='evolucaoclinica',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolucoes', to='accounts.orcamento'),
        ),
    ]
