# Generated by Django 6.0.5 on 2026-06-28 14:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_evolucaoclinica_item_orcamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Tratamento', max_length=150, verbose_name='Título')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado')], default='ATIVO', max_length=15, verbose_name='Status')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Data de início')),
                ('data_encerramento', models.DateField(blank=True, null=True, verbose_name='Data de encerramento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamentos', to='accounts.paciente')),
            ],
            options={
                'verbose_name': 'Tratamento',
                'verbose_name_plural': 'Tratamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
