# Generated by Django 6.0.5 on 2026-06-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_tratamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamento',
            name='titulo',
            field=models.CharField(default='Tratamento Inicial', max_length=150, verbose_name='Título'),
        ),
    ]
