# Generated by Django 6.0.5 on 2026-06-28 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_alter_tratamento_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='tratamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='accounts.tratamento'),
        ),
    ]
