# Generated by Django 6.0.5 on 2026-06-29 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_orcamento_tratamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucaoclinica',
            name='tratamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes', to='accounts.tratamento'),
        ),
    ]
