# Generated by Django 6.0.5 on 2026-07-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_evolucaoclinica_tratamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamento',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=15, verbose_name='Status'),
        ),
    ]
