# Generated by Django 6.0.5 on 2026-07-09 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_alter_tratamento_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contareceber',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDO', 'Recebido'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='parcelas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado')], default='ATIVO', max_length=15, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=50)),
                ('acao', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('cadastro', 'Cadastro'), ('edicao', 'Edição'), ('exclusao', 'Exclusão'), ('cancelamento', 'Cancelamento'), ('aprovacao', 'Aprovação'), ('recebimento', 'Recebimento'), ('pagamento', 'Pagamento'), ('impressao', 'Impressão'), ('pdf', 'PDF'), ('excel', 'Excel'), ('backup', 'Backup'), ('restauracao', 'Restauração'), ('outro', 'Outro')], max_length=20)),
                ('nivel', models.CharField(choices=[('info', 'Informação'), ('atencao', 'Atenção'), ('importante', 'Importante'), ('critico', 'Crítico')], default='info', max_length=15)),
                ('descricao', models.TextField()),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
                'ordering': ['-data_hora'],
            },
        ),
    ]
