# Generated by Django 6.0.5 on 2026-07-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_perfil'),
    ]

    operations = [
    ]
