# Generated by Django 6.0.5 on 2026-07-14 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_criar_perfis_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='accounts.perfil'),
        ),
    ]
