# Generated by Django 6.0.5 on 2026-07-15 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_perfilusuario_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('icone', models.CharField(blank=True, max_length=50, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='perfil',
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualizar', models.BooleanField(default=False)),
                ('inserir', models.BooleanField(default=False)),
                ('editar', models.BooleanField(default=False)),
                ('excluir', models.BooleanField(default=False)),
                ('exportar', models.BooleanField(default=False)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='accounts.modulo')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='accounts.perfil')),
            ],
            options={
                'verbose_name': 'Permissão',
                'verbose_name_plural': 'Permissões',
                'ordering': ['perfil', 'modulo'],
                'unique_together': {('perfil', 'modulo')},
            },
        ),
    ]
