# Generated by Django 6.0.5 on 2026-07-15 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_modulo_remove_perfilusuario_perfil_permissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='perfil_acesso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='accounts.perfil', verbose_name='Perfil de Acesso'),
        ),
    ]
