# Generated by Django 6.0.5 on 2026-07-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0081_perfilusuario_perfil_acesso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['tipo', 'nome'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AddField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('operacional', 'Operacional'), ('administrativo', 'Administrativo')], default='operacional', max_length=20, verbose_name='Tipo do Perfil'),
        ),
    ]
