# Generated by Django 6.0.5 on 2026-07-15 23:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0082_alter_perfil_options_perfil_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['grupo', 'ordem', 'nome'], 'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='descricao',
        ),
        migrations.AddField(
            model_name='modulo',
            name='atualizado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='codigo',
            field=models.CharField(default='',max_length=50,verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='grupo',
            field=models.CharField(default='Geral', max_length=50, verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='icone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
    ]
