# Generated by Django 6.0.5 on 2026-07-18 19:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0083_alter_modulo_options_remove_modulo_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissao',
            name='aprovar',
            field=models.BooleanField(default=False, verbose_name='Aprovar'),
        ),
        migrations.AddField(
            model_name='permissao',
            name='financeiro',
            field=models.BooleanField(default=False, verbose_name='Financeiro'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='grupo',
            field=models.CharField(default='GERAL', max_length=50, verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='icone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='permissao',
            name='editar',
            field=models.BooleanField(default=False, verbose_name='Editar'),
        ),
        migrations.AlterField(
            model_name='permissao',
            name='excluir',
            field=models.BooleanField(default=False, verbose_name='Excluir'),
        ),
        migrations.AlterField(
            model_name='permissao',
            name='exportar',
            field=models.BooleanField(default=False, verbose_name='Exportar'),
        ),
        migrations.AlterField(
            model_name='permissao',
            name='inserir',
            field=models.BooleanField(default=False, verbose_name='Inserir'),
        ),
        migrations.AlterField(
            model_name='permissao',
            name='visualizar',
            field=models.BooleanField(default=False, verbose_name='Visualizar'),
        ),
    ]
