# Generated by Django 6.0.5 on 2026-07-19 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0084_permissao_aprovar_permissao_financeiro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissao',
            name='financeiro',
        ),
    ]
