# Generated by Django 6.0.5 on 2026-07-23 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0085_remove_permissao_financeiro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='percentual_comissao',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='Percentual de comissão do dentista.', max_digits=5, verbose_name='Comissão (%)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(blank=True, null=True, verbose_name='Alergias'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='carteirinha',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Carteirinha'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cidade',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='convenio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Convênio'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf_responsavel',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Responsável'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dentista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Dentista Responsável'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='medicamentos',
            field=models.TextField(blank=True, null=True, verbose_name='Medicamentos em uso'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='responsavel',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone_responsavel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Responsável'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='dentista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to=settings.AUTH_USER_MODEL),
        ),
    ]
