# Generated by Django 6.0.5 on 2026-07-23 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0086_perfilusuario_percentual_comissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='accounts.perfilusuario'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='accounts.fornecedor'),
        ),
    ]
