# Generated by Django 6.0.5 on 2026-07-23 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0087_contapagar_profissional_alter_contapagar_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='conta_receber',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comissao', to='accounts.contareceber'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='parcela',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='total_parcelas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
