# Generated by Django 6.0.5 on 2026-07-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_contapagar_conta_receber_alter_contareceber_parcela_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='acrescimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Acréscimo'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto'),
        ),
    ]
