# Generated by Django 6.0.5 on 2026-07-24 18:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0089_orcamento_acrescimo_alter_orcamento_desconto'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivroCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('origem', models.CharField(choices=[('CONTA_RECEBER', 'Conta a Receber'), ('CONTA_PAGAR', 'Conta a Pagar'), ('COMPRA', 'Compra'), ('COMISSAO', 'Comissão'), ('AJUSTE', 'Ajuste'), ('MANUAL', 'Manual')], max_length=30)),
                ('descricao', models.CharField(max_length=255)),
                ('entrada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('saida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livro_caixa', to='accounts.compra')),
                ('conta_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_livro_caixa', to='accounts.contapagar')),
                ('conta_receber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_livro_caixa', to='accounts.contareceber')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livro_caixa', to='accounts.fornecedor')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livro_caixa', to='accounts.paciente')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livro_caixa', to='accounts.perfilusuario')),
            ],
            options={
                'verbose_name': 'Livro Caixa',
                'verbose_name_plural': 'Livro Caixa',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
