# Generated by Django 6.0.5 on 2026-07-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0090_livrocaixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='meta_mensal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Meta mensal de produção do dentista.', max_digits=10, verbose_name='Meta Mensal (R$)'),
        ),
    ]
