# Generated by Django 6.0.5 on 2026-07-27 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0091_perfilusuario_meta_mensal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=10)),
                ('observacoes', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixas_diarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caixa Diário',
                'verbose_name_plural': 'Caixas Diários',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
