# Generated by Django 6.0.5 on 2026-07-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0093_caixa_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixadiario',
            name='reaberto',
            field=models.BooleanField(default=False),
        ),
    ]
