# Generated by Django 6.0.5 on 2026-07-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0094_caixadiario_reaberto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixadiario',
            name='reaberto',
        ),
    ]
