# Generated by Django 6.0.5 on 2026-07-27 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0095_remove_caixadiario_reaberto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mês')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('meta_financeira', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Meta Financeira')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_dentista', to=settings.AUTH_USER_MODEL, verbose_name='Dentista')),
            ],
            options={
                'verbose_name': 'Meta do Dentista',
                'verbose_name_plural': 'Metas dos Dentistas',
                'ordering': ['-ano', '-mes', 'dentista__first_name'],
                'unique_together': {('dentista', 'mes', 'ano')},
            },
        ),
    ]
