# Generated by Django 6.0.5 on 2026-08-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0096_metadentista'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('mes', models.PositiveIntegerField(verbose_name='Mês')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Meta')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Meta da Clínica',
                'verbose_name_plural': 'Metas da Clínica',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('ano', 'mes')},
            },
        ),
    ]
