# Generated by Django 6.0.5 on 2026-08-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0097_metaclinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaclinica',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Meta'),
        ),
    ]
