# Generated by Django 6.0.5 on 2026-08-05 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0098_alter_metaclinica_valor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadentista',
            options={'ordering': ['-ano', '-mes', 'dentista'], 'verbose_name': 'Meta do Dentista', 'verbose_name_plural': 'Metas dos Dentistas'},
        ),
        migrations.AlterUniqueTogether(
            name='metadentista',
            unique_together={('dentista', 'ano', 'mes')},
        ),
        migrations.AddField(
            model_name='metadentista',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='metadentista',
            name='meta_pacientes',
            field=models.PositiveIntegerField(default=0, verbose_name='Meta de Novos Pacientes'),
        ),
        migrations.AddField(
            model_name='metadentista',
            name='meta_procedimentos',
            field=models.PositiveIntegerField(default=0, verbose_name='Meta de Procedimentos'),
        ),
        migrations.AddField(
            model_name='metadentista',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='metadentista',
            name='ano',
            field=models.PositiveIntegerField(verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='metadentista',
            name='dentista',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'DENTISTA'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.perfilusuario', verbose_name='Dentista'),
        ),
        migrations.AlterField(
            model_name='metadentista',
            name='mes',
            field=models.PositiveIntegerField(verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='metadentista',
            name='meta_financeira',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Meta Financeira'),
        ),
        migrations.RemoveField(
            model_name='metadentista',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='metadentista',
            name='observacoes',
        ),
    ]
