# Generated by Django 6.0.5 on 2026-08-07 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0099_alter_metadentista_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadentista',
            name='dentista',
            field=models.ForeignKey(limit_choices_to={'ativo': True, 'tipo_usuario': 'dentista'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.perfilusuario', verbose_name='Dentista'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('origem', models.CharField(choices=[('GOOGLE', 'Google Ads'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('WHATSAPP', 'WhatsApp'), ('SITE', 'Site'), ('INDICACAO', 'Indicação'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('CONTATADO', 'Contatado'), ('AGENDADO', 'Agendado'), ('CONVERTIDO', 'Convertido'), ('PERDIDO', 'Perdido')], default='NOVO', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ultimo_contato', models.DateTimeField(blank=True, null=True)),
                ('proximo_contato', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
