# Generated by Django 6.0.5 on 2026-08-07 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0100_alter_metadentista_dentista_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('canal', models.CharField(choices=[('GOOGLE', 'Google Ads'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('WHATSAPP', 'WhatsApp'), ('SITE', 'Site'), ('EMAIL', 'E-mail Marketing'), ('OUTRO', 'Outro')], default='GOOGLE', max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('investimento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativa', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('PAUSADA', 'Pausada'), ('FINALIZADA', 'Finalizada')], default='ATIVA', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
