# Generated by Django 6.0.5 on 2026-08-08 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0103_alter_campanhamarketing_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='campanha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='accounts.campanhamarketing', verbose_name='Campanha'),
        ),
    ]
