# Generated by Django 6.0.5 on 2026-08-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0104_lead_campanha'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanhamarketing',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='campanhas/'),
        ),
    ]
