# Generated by Django 6.0.5 on 2026-08-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0105_campanhamarketing_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanhamarketing',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='marketing/campanhas/', verbose_name='Imagem da campanha'),
        ),
    ]
