# Generated by Django 6.0.5 on 2026-08-10 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0106_alter_campanhamarketing_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizacaoCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessao', models.CharField(db_index=True, max_length=100, verbose_name='Sessão')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade de acessos')),
                ('primeiro_acesso', models.DateTimeField(auto_now_add=True, verbose_name='Primeiro acesso')),
                ('ultimo_acesso', models.DateTimeField(auto_now=True, verbose_name='Último acesso')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='accounts.campanhamarketing', verbose_name='Campanha')),
            ],
            options={
                'verbose_name': 'Visualização da Campanha',
                'verbose_name_plural': 'Visualizações das Campanhas',
                'constraints': [models.UniqueConstraint(fields=('campanha', 'sessao'), name='unique_visualizacao_campanha_sessao')],
            },
        ),
    ]
